trigger:
- master  # Puedes cambiar esto según la rama que desees

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Installing Node.js...
  displayName: 'Instalar Node.js'
  
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Instalar Node.js'

- script: echo Installing dependencies...
  displayName: 'Instalar dependencias'
  
- script: npm install
  displayName: 'Instalar dependencias npm'

- script: echo Building the React app...
  displayName: 'Construir la aplicación React'
  
- script: npm run build
  displayName: 'Ejecutar comando de construcción'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'  # Ajusta esta ruta según la ubicación de tus archivos de construcción
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Empaquetar archivos'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'react-app'
    publishLocation: 'Container'
  displayName: 'Publicar artefactos de compilación'